#%%
def base_counter(dna_seq:str):
    
    dna_seq = dna_seq.upper()

    A_count = dna_seq.count('A')
    C_count = dna_seq.count('C')
    G_count = dna_seq.count('G')
    T_count = dna_seq.count('T')

    print(
        A_count,
        C_count,
        G_count,
        T_count
    )
    
# %%
base_counter("CTGGTGGACAAACACAATATGCCATACCGCACCGATTTTAATGTCCCCTGATAACACAGTGGGTCGATGTTCCGCACGCTAAAGGATCTGAATCACAGTAGAAAGTTACCCACGCAAGCGCCATTCGATTCTGTTAATGGTTGTGTAGGGTCCGTGAGAGAATGCAAATGTACAAAGGGCGCCTATGAGCATCTGACCTCCTAAACTAAAGCTTCATACGTAACTGTAATTACCTCAGTACAAACTACCAACGAAGTTGAAACCGTTAACTGGACAACAAGTGGCATTTAGTATGCTCTCAGTTTATACGCTCCGGTTCCTGTGGTGCAGTGTATCTTGTGTACTAGCGGTCCCTCGCAAGCGAGGGACTGCCGTTCTTGAGCCGCGACGCTTGCTTCCCTCATCCTAATTCGTCTAGCGAGCGCTATTTGGTCACCTGCAACTAGTTCCTCACCCCTTTAATGATGGCCCCTGAACGATATTCAACTCCCCGCCGAGGGCTGAGCGGATGTGTTCATGCTTCGTATTCAACAAGCCAGCTCCCTCATAGCCATAAGTTCATACAATCCGCTCTTTCGGAAGAGGTCCATACCCAGTGGATCAGTTTCCCCATGCAGTTTAGATTCAGACCTGTACTCCCCTTAGCTGCTGCGACGTGTAATTTTATGGGTGAGTAGTGCTGCACCCCCAATGTCGCACCAGGGAAATTCACGCGCCTCGCACGTACAGTACCTATGGGAACACAACCGTGCTGCCTCTGAGCGAAACGACGTAGTTGTTGACAATTGAGGAAACAACTGCGTAATTTATCAGCTTCTGGCTTTGGCGGGCCCGGAGATCACGTCTCATAACACAGCGTTTTCTTTACTTGACTCGCAGTCAGCCCTC")
# %%
