'''
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").
Given: A DNA string s of length at most 1000 bp.
Return: The reverse complement sc of s.
'''

#%% 
def rev_comp(dna_seq:str): 
    dna_seq = dna_seq.upper()
    
    complements = {
        "A":"T",
        "C":"G",
        "T":"A",
        "G":"C"
    }
    
    # for base in reversed(dna_seq) use the complements dictionary to convert the character, then add it to a growing str
    reverse_complement = "".join(complements.get(base, base) for base in reversed(dna_seq))
    print(reverse_complement)
# %%
rev_comp("CGTAGACGTTATGGAACGGTTCGTCCCTACGGGGCCCGGCCCGTTCTTCACGGAGGCTGGGCATCCAAGTCGGATCAAAGGACACGCAGCCATCGCCACTATACCAATCTTTTTCTTGGACTTCTGATCACGCCAAAGTCATTCCCTACCGATAACGAAGTGGCAGGTTGCGCTCAATCATGAATTACTAATGACTTTTGAGTATTATATAGTTCATGCTGGCCGGGCCTGTGAGCCAGCCAGTAAAAGTAAAACTCTCCCGCGACGCTGTCTCGGCGACATGTTATCGCCCCAGGCGGGATCCGCAAACGCGAGCTTATGGTCGTTGTCTCAAACTTGCGCACCAGTGCGCTATATTCACGGTTGATACCAACTTTCATCGACTTCGGAGGTAGAAGCGGCCCGAAGGGCACGTTGATGAGGGGCGCGGACCAGACTACACTTTACGAAGATCTGTTGCTGCTCAGGTAAGTGGGGTTGAGTGATGCCATAGGACTGCCGTGAGTGCGTTTTTCTTCATGAACAATGTATCCTCTGCAGTTTGAGTTGTTTGAATGGTTTCTTTCATCCGTCGGCTTTGATGATAAAGTTAGTGGAATGTTACTCGGTTAGTCTCTGCTGATTGATGCCCAACATTTGGATCTGGAACATGCGTATGTCCAAAGTAGAACCCACGTTCGACCATACGTCTAGATAGCTGAAGGTATCATGTGGTGAAAACACATCTGTGGTAGCGCCCATGGAATCTTCGACGAGGCGAGATGTGTCATACGTGCTCCGAATGGCTCGCAGATTACGGCGAATACTCGAAATGTGTCAGAGGTAAAAGATAAGAAGTGCATGTGTTCAGACATGCCTGCTCATGAGGTAGCCGCCATGCGTGTGCCTGAGGACTATTCATGCCGATGAGTG")
# %%
